# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\calibracao_cone.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def button_search(self, line_edit):
        fileName, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Open File", "", "All Files (*);;Python Files(*.py)")

        if fileName:
            line_edit.setText(fileName)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 351)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.opcao1 = QtWidgets.QLabel(self.centralwidget)
        self.opcao1.setGeometry(QtCore.QRect(10, 10, 841, 31))
        self.opcao1.setAlignment(QtCore.Qt.AlignCenter)
        self.opcao1.setObjectName("opcao1")
        self.pg1_prox = QtWidgets.QPushButton(self.centralwidget)
        self.pg1_prox.setGeometry(QtCore.QRect(470, 260, 121, 41))
        self.pg1_prox.setObjectName("pg1_prox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 80, 641, 143))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cone1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.cone1.setObjectName("cone1")
        self.horizontalLayout.addWidget(self.cone1)
        self.bt_cone1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bt_cone1.setObjectName("bt_cone1")
        self.horizontalLayout.addWidget(self.bt_cone1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cone2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.cone2.setObjectName("cone2")
        self.horizontalLayout_2.addWidget(self.cone2)
        self.bt_cone2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bt_cone2.setObjectName("bt_cone2")
        self.horizontalLayout_2.addWidget(self.bt_cone2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cone3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.cone3.setObjectName("cone3")
        self.horizontalLayout_3.addWidget(self.cone3)
        self.bt_cone3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bt_cone3.setObjectName("bt_cone3")
        self.horizontalLayout_3.addWidget(self.bt_cone3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.cone4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.cone4.setObjectName("cone4")
        self.horizontalLayout_4.addWidget(self.cone4)
        self.bt_cone4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bt_cone4.setObjectName("bt_cone4")
        self.horizontalLayout_4.addWidget(self.bt_cone4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pg1_prox_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pg1_prox_2.setGeometry(QtCore.QRect(290, 260, 121, 41))
        self.pg1_prox_2.setObjectName("pg1_prox_2")

        self.bt_cone1.clicked.connect(lambda: self.button_search(self.cone1))
        self.bt_cone2.clicked.connect(lambda: self.button_search(self.cone2))
        self.bt_cone3.clicked.connect(lambda: self.button_search(self.cone3))
        self.bt_cone4.clicked.connect(lambda: self.button_search(self.cone4))

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.opcao1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">3. Opção de registro</span></p></body></html>"))
        self.pg1_prox.setText(_translate("MainWindow", "Próximo ->"))
        self.label.setText(_translate("MainWindow", "jogador 1:"))
        self.bt_cone1.setText(_translate("MainWindow", "pesquisar"))
        self.label_2.setText(_translate("MainWindow", "jogador 2:"))
        self.bt_cone2.setText(_translate("MainWindow", "pesquisar"))
        self.label_3.setText(_translate("MainWindow", "jogador 3:"))
        self.bt_cone3.setText(_translate("MainWindow", "pesquisar"))
        self.label_4.setText(_translate("MainWindow", "jogador 4:"))
        self.bt_cone4.setText(_translate("MainWindow", "pesquisar"))
        self.pg1_prox_2.setText(_translate("MainWindow", "<- Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
